---
default_language_version:
  python: python3

exclude: ^(doc/_static/.*|doc/_themes/.*)$
minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
        exclude: >
          (?x)^(
            pkg/macos/pkg-resources/.*\.rtf
          )$

      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=auto]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
        exclude: changelog/.*
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.
        exclude: >
          (?x)^(
            templates/.*
          )$
      - id: check-case-conflict   # Check for files with names that would conflict on a
                                  # case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-json            # Attempts to load all json files to verify syntax.
      - id: check-symlinks        # Checks for symlinks which do not point to anything.
      - id: debug-statements      # Check for debugger imports and py37+ breakpoint() calls in python source.
        exclude: >
          (?x)^(
            templates/.*
          )$
      - id: fix-byte-order-marker # removes UTF-8 byte order marker
      - id: forbid-submodules     # forbids any submodules in the repository.
      - id: fix-encoding-pragma   # Remove `# -*- coding: utf-8 -*-` from the top of python files.
        args:
          - --remove
        exclude: >
          (?x)^(
            salt/ext/.*
          )$

  # ----- Formatting ---------------------------------------------------------------------------->
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.7+, drop six usage and Py2 support
        args: [--py3-plus, --keep-mock]
        exclude: src/saltext/vcenter/version.py

  - repo: https://github.com/saltstack/pre-commit-remove-import-headers
    rev: 1.1.0
    hooks:
      - id: remove-import-headers

  - repo: local
    hooks:
      - id: check-cli-examples
        name: Check CLI examples on execution modules
        entry: python .pre-commit-hooks/check-cli-examples.py
        language: system
        files: ^src/saltext/vcenter/modules/.*\.py$

  - repo: local
    hooks:
      - id: check-docs
        name: Check rST doc files exist for modules/states
        entry: python .pre-commit-hooks/make-autodocs.py
        language: system
        pass_filenames: false

  - repo: https://github.com/s0undt3ch/salt-rewrite
    # Automatically rewrite code with known rules
    rev: "2.2.0"
    hooks:
      - id: salt-rewrite
        alias: rewrite-docstrings
        name: Salt extensions docstrings auto-fixes
        files: ^src/saltext/vcenter/.*\.py$
        args: [--silent, -F, fix_docstrings]

      - id: salt-rewrite
        alias: rewrite-tests
        name: Rewrite Salt's Test Suite
        files: ^tests/.*\.py$
        args: [--silent, -E, fix_asserts, -E, fix_docstrings]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
        args: [
          --py3-plus,
        ]
        exclude: src/saltext/vcenter/version.py

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l 100]
        exclude: src/saltext/vcenter/version.py
        additional_dependencies:
          - click<8.1.0

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^docs/.*\.rst
        additional_dependencies: [black==20.8b1]

  - repo: https://github.com/myint/rstcheck
    rev: 3f92957
    hooks:
      - id: rstcheck
        name: Check reST files using rstcheck
        args: [--report=warning, --ignore-directives=automodule]
        additional_dependencies: [sphinx]
  # <---- Formatting -----------------------------------------------------------------------------

  # ----- Security ------------------------------------------------------------------------------>
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against the code base
        args: [--silent, -lll, --skip, "B701,B324"]
        exclude: src/saltext/vcenter/version.py
        additional_dependencies: ['importlib_metadata<5']
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, "B701,B324"]
        files: ^tests/.*
        additional_dependencies: ['importlib_metadata<5']
  # <---- Security -------------------------------------------------------------------------------

  # ----- Code Analysis ------------------------------------------------------------------------->
  # forget you, lint.
#  - repo: https://github.com/saltstack/mirrors-nox
#    rev: v2020.8.22
#    hooks:
#      - id: nox
#        alias: lint-src
#        name: Lint Source Code
#        files: ^((setup|noxfile)|src/.*)\.py$
#        require_serial: True
#        args:
#          - -e
#          - lint-code-pre-commit
#          - --
#
#  - repo: https://github.com/saltstack/mirrors-nox
#    rev: v2020.8.22
#    hooks:
#      - id: nox
#        alias: lint-tests
#        name: Lint Tests
#        files: ^tests/.*\.py$
#        require_serial: True
#        args:
#          - -e
#          - lint-tests-pre-commit
#          - --
  # <---- Code Analysis --------------------------------------------------------------------------

  # ----- Static Test Requirements -------------------------------------------------------------->
  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
    rev: '4.8'
    hooks:
      - id: pip-tools-compile
        alias: compile-3.7-test-requirements
        name: Py3.7 Test Requirements
        files: ^requirements/tests.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.7
          - --platform=linux
          - requirements/tests.in

      - id: pip-tools-compile
        alias: compile-3.8-test-requirements
        name: Py3.8 Test Requirements
        files: ^requirements/tests.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.8
          - --platform=linux
          - requirements/tests.in

      - id: pip-tools-compile
        alias: compile-3.9-test-requirements
        name: Py3.9 Test Requirements
        files: ^requirements/tests.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.9
          - --platform=linux
          - requirements/tests.in

      - id: pip-tools-compile
        alias: compile-3.10-test-requirements
        name: Py3.10 Test Requirements
        files: ^requirements/tests.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.10
          - --platform=linux
          - requirements/tests.in
  # <---- Static Test Requirements ---------------------------------------------------------------

  # ----- Static Lint Requirements -------------------------------------------------------------->
      - id: pip-tools-compile
        alias: compile-3.7-test-requirements
        name: Py3.7 Lint Requirements
        files: ^requirements/lint.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.7
          - --platform=linux
          - requirements/lint.in

      - id: pip-tools-compile
        alias: compile-3.8-test-requirements
        name: Py3.8 Lint Requirements
        files: ^requirements/lint.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.8
          - --platform=linux
          - requirements/lint.in

      - id: pip-tools-compile
        alias: compile-3.9-test-requirements
        name: Py3.9 Lint Requirements
        files: ^requirements/lint.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.9
          - --platform=linux
          - requirements/lint.in

      - id: pip-tools-compile
        alias: compile-3.10-test-requirements
        name: Py3.10 Lint Requirements
        files: ^requirements/lint.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.10
          - --platform=linux
          - requirements/lint.in
  # <---- Static Lint Requirements ---------------------------------------------------------------

  # ----- Static Docs Requirements -------------------------------------------------------------->
      - id: pip-tools-compile
        alias: compile-3.7-test-requirements
        name: Py3.7 Docs Requirements
        files: ^requirements/docs.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.7
          - --platform=linux
          - requirements/docs.in

      - id: pip-tools-compile
        alias: compile-3.8-test-requirements
        name: Py3.8 Docs Requirements
        files: ^requirements/docs.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.8
          - --platform=linux
          - requirements/docs.in

      - id: pip-tools-compile
        alias: compile-3.9-test-requirements
        name: Py3.9 Docs Requirements
        files: ^requirements/docs.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.9
          - --platform=linux
          - requirements/docs.in

      - id: pip-tools-compile
        alias: compile-3.10-test-requirements
        name: Py3.10 Docs Requirements
        files: ^requirements/docs.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.10
          - --platform=linux
          - requirements/docs.in
  # <---- Static Docs Requirements ---------------------------------------------------------------
