
name: Test PyPI Publish

on:
  release:
    types: [prereleased]

jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Nox
      run: |
        python -m pip install nox

    - name: Build a binary wheel and a source tarball
      run: |
        nox -e build

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://test.pypi.org/legacy/
        print-hash: true
        skip-existing: true
        verbose: true
        verify-metadata: true
